[build]
  # Directorio donde est치n los archivos construidos
  publish = "dist"

  # Comando para construir la aplicaci칩n
  command = "npm run build"

[build.environment]
  # Variables de entorno para el build
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Configuraci칩n para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para archivos est치ticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"